/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class InterfazSalidas extends javax.swing.JInternalFrame {
control_existencias ctrl = new control_existencias();
     control_existencias con;
     String itemSeleecionado;
    private Object [][] datostabla;   
    public InterfazSalidas(control_existencias con) {
        initComponents();
        this.con = con;
        limpiar();
        serie.setVisible(false);
numserie.setVisible(false);
buscar.setVisible(false);
        registrar.setVisible(false);
    }
public void tiposalida(){
if(equipog.isSelected()){
    serie.setVisible(true);
numserie.setVisible(true);
buscar.setVisible(true);
accesorios.setEnabled(false);
equipog.setEnabled(false);
tiposal.setEnabled(false);
statusE.setVisible(true);
lstatus.setVisible(true);
soporte.setVisible(true);
soporte.setEnabled(false);
label.setText("Comentarios:");
} else if(accesorios.isSelected()){
    serie.setVisible(false);
numserie.setVisible(false);
buscar.setVisible(false);
nombre.setVisible(false);
lnombre.setVisible(false);
udn.setVisible(false);
ludn.setVisible(false);
statusE.setVisible(false);
lstatus.setVisible(false);
    accesorios.setEnabled(false);
equipog.setEnabled(false);
tiposal.setEnabled(false);
calendario.setEnabled(true);
des.setEnabled(true);
soporte.setVisible(true);
soporte.setEnabled(true);
motivo.setEnabled(true);
guia.setEnabled(true);
statusE.setEnabled(true);
Date now = new Date(System.currentTimeMillis());
SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
System.out.println(date.format(now));
calendario.setDate(now);
label.setText("Tipo de Accesorio:");
raccesorios.setVisible(false);
raccesorios.setVisible(true);
}
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        numserie = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        serie = new javax.swing.JTextField();
        guia = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        calendario = new com.toedter.calendar.JDateChooser();
        lnombre = new javax.swing.JLabel();
        ludn = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo = new javax.swing.JTextArea();
        statusE = new javax.swing.JComboBox();
        lstatus = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        udn = new javax.swing.JTextField();
        tiposal = new javax.swing.JLabel();
        equipog = new javax.swing.JCheckBox();
        accesorios = new javax.swing.JCheckBox();
        cancelar = new javax.swing.JButton();
        soporte = new javax.swing.JComboBox<>();
        raccesorios = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setIconifiable(true);
        setTitle("Salida");
        setMinimumSize(new java.awt.Dimension(105, 34));
        setPreferredSize(new java.awt.Dimension(780, 500));

        numserie.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        numserie.setText("Número de serie");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Destinatario");

        label.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de Salida");

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        registrar.setForeground(new java.awt.Color(102, 102, 102));
        registrar.setText("Registrar");
        registrar.setOpaque(false);
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Remitente");

        calendario.setDateFormatString("yyyy/MM/d");

        lnombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lnombre.setText("Nombre");

        ludn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ludn.setText("UDN");

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("No. de guia");

        motivo.setColumns(20);
        motivo.setRows(5);
        motivo.setToolTipText("Moticvo");
        jScrollPane1.setViewportView(motivo);

        statusE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------------", "Asignado", "Dañado", "En bodega" }));
        statusE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusEActionPerformed(evt);
            }
        });

        lstatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lstatus.setText("Status");

        nombre.setEditable(false);
        nombre.setEnabled(false);

        udn.setEditable(false);
        udn.setEnabled(false);

        tiposal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tiposal.setText("Tipo de salida:");

        equipog.setText("Equipo de garantía");
        equipog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipogActionPerformed(evt);
            }
        });

        accesorios.setText("Accesorios");
        accesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriosActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        soporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------------" }));
        soporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soporteActionPerformed(evt);
            }
        });

        raccesorios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        raccesorios.setText("Registrar");
        raccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raccesoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(raccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addGap(78, 78, 78)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(guia, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(soporte, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)
                        .addComponent(lstatus)
                        .addGap(18, 18, 18)
                        .addComponent(statusE, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnombre)
                                    .addComponent(ludn))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(udn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numserie)
                                        .addGap(18, 18, 18)
                                        .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tiposal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(equipog)
                                        .addGap(18, 18, 18)
                                        .addComponent(accesorios)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelar)
                                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tiposal)
                            .addComponent(equipog)
                            .addComponent(accesorios)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numserie)
                    .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ludn)
                    .addComponent(udn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(soporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lstatus)
                        .addComponent(statusE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void limpiar()
    {
calendario.setEnabled(false);
serie.setText("");
raccesorios.setVisible(false);
nombre.setEnabled(false);
udn.setEnabled(false);
des.setEnabled(false);
soporte.setEnabled(false);
motivo.setEnabled(false);
guia.setEnabled(false);
statusE.setEnabled(false);
statusE.setVisible(true);
soporte.setVisible(true);
registrar.setVisible(false);
nombre.setText("");
udn.setText("");
des.setText("");
motivo.setText(""); 
guia.setText(""); 
Object[] resp = con.combox("soporte","idsoporte");
        soporte.removeAllItems();
        for(int i=0;i<resp.length;i++)
        {
        soporte.addItem((String) resp[i]);
        }
    }
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
String s=serie.getText();
        System.out.println(s);
String status=ctrl.statusbdg(s);
if(ctrl.existe_equipo("'"+s+"'")){
if(status.equals("4")){
registrar.setVisible(true);
nombre.setText(con.ingresa_nombre("'"+s+"'"));
udn.setText(con.ingresa_udn("'"+s+"'"));

calendario.setEnabled(true);
des.setEnabled(true);
soporte.setEnabled(true);
motivo.setEnabled(true);
guia.setEnabled(true);
statusE.setEnabled(true);
Date now = new Date(System.currentTimeMillis());
SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
System.out.println(date.format(now));
calendario.setDate(now);
}
else{
JOptionPane.showMessageDialog(null,"El equipo con serie "+'"'+s+'"'+" no tiene status de garantía");
limpiar();
}
//calendario.setDateFormatString(fecha);
}else{
JOptionPane.showMessageDialog(null,"La serie "+'"'+s+'"'+" no existe");
serie.setVisible(true);
numserie.setVisible(true);
buscar.setVisible(true);
limpiar();
}
    }//GEN-LAST:event_buscarActionPerformed
public static String convertTostring(Date Date)
        {
            DateFormat df;
            String fech = null;
            df = new SimpleDateFormat("yyyy-MM-d");
            fech = df.format(Date);
            return fech;
        }
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
String fa,is,so;
so=soporte.getSelectedItem().toString();
     String bdg=" ";
    fa = convertTostring(calendario.getDate());
    is=statusE.getSelectedItem().toString();
        if(serie.equals("")||motivo.equals("")||soporte.getSelectedItem().equals("")||des.equals("")||guia.equals(""))
         {          
            JOptionPane.showMessageDialog(null, "Hay campos vacios obligatorios"); 
         }else if( con.actualizarsg(fa,motivo.getText(),so,des.getText(),guia.getText(),serie.getText())&&con.acualizarEntradas(is,motivo.getText(),serie.getText())&&con.acualizarEntradafG("0",nombre.getText(),serie.getText()))
         {          
            JOptionPane.showMessageDialog(null,"Equipo registrado");
            limpiar();
            accesorios.setEnabled(true);
equipog.setEnabled(true);
accesorios.setSelected(false);
equipog.setSelected(false);
tiposal.setEnabled(true); 
serie.setVisible(false);
numserie.setVisible(false);
buscar.setVisible(false);
label.setText("");
            registrar.setVisible(false);
        }else{JOptionPane.showMessageDialog(this, "Ocurrio un problema, registro no realizado");} 
         
// TODO add your handling code here:
    }//GEN-LAST:event_registrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void statusEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusEActionPerformed

    private void equipogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipogActionPerformed
tiposalida();        // TODO add your handling code here:
    }//GEN-LAST:event_equipogActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
accesorios.setEnabled(true);
equipog.setEnabled(true);
accesorios.setSelected(false);
equipog.setSelected(false);
tiposal.setEnabled(true); 
serie.setVisible(false);
numserie.setVisible(false);
buscar.setVisible(false);
label.setText("");
limpiar();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void accesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriosActionPerformed
tiposalida();        // TODO add your handling code here:
    }//GEN-LAST:event_accesoriosActionPerformed

    private void soporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soporteActionPerformed

    private void raccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raccesoriosActionPerformed
String fa,is,so;
so=soporte.getSelectedItem().toString();
     String bdg=" ";
    fa = convertTostring(calendario.getDate());
    is=statusE.getSelectedItem().toString();
        if(motivo.equals("")||soporte.getSelectedItem().equals("")||des.equals("")||guia.equals(""))
         {          
            JOptionPane.showMessageDialog(null, "Hay campos vacios obligatorios"); 
         }else if( con.salidaac(guia.getText(),fa,motivo.getText(),des.getText(),so))
         {          
            JOptionPane.showMessageDialog(null,"Equipo registrado");
            limpiar();
            accesorios.setEnabled(true);
equipog.setEnabled(true);
accesorios.setSelected(false);
equipog.setSelected(false);
tiposal.setEnabled(true); 
serie.setVisible(false);
numserie.setVisible(false);
buscar.setVisible(false);
label.setText("");
        }else{JOptionPane.showMessageDialog(this, "Ocurrio un problema, registro no realizado");} 
        // TODO add your handling code here:
    }//GEN-LAST:event_raccesoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox accesorios;
    private javax.swing.JButton buscar;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField des;
    private javax.swing.JCheckBox equipog;
    private javax.swing.JTextField guia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel lstatus;
    private javax.swing.JLabel ludn;
    private javax.swing.JTextArea motivo;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel numserie;
    private javax.swing.JButton raccesorios;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField serie;
    private javax.swing.JComboBox<String> soporte;
    private javax.swing.JComboBox statusE;
    private javax.swing.JLabel tiposal;
    private javax.swing.JTextField udn;
    // End of variables declaration//GEN-END:variables
}
